FROM phcerdan/sgext-linux-base
LABEL MAINTAINER="Pablo Hernandez Cerdan <pablo.hernandez.cerdan@outlook.com>"

###################### SGEXT #############
ENV SGEXT_BUILD_DIR ${BUILD_PATH}/SGEXT-build
ENV SGEXT_SRC_FOLDER_NAME SGEXT-src
ENV SGEXT_SRC_DIR ${BUILD_PATH}/${SGEXT_SRC_FOLDER_NAME}

# Copy files from current repo into the docker container
WORKDIR ${SGEXT_BUILD_DIR}
COPY . ${SGEXT_SRC_DIR}

# intel-tbb (installed via yum)
RUN gosu root yum install -y tbb-devel
# ENV TBB_ROOT /opt/intel/tbb
RUN cmake \
        -G Ninja \
        -DCMAKE_BUILD_TYPE:STRING=Release \
        -DSG_BUILD_TESTING:BOOL=ON \
        -DSG_MODULE_ANALYZE:BOOL=ON \
        -DSG_MODULE_COMPARE:BOOL=ON \
        -DSG_MODULE_LOCATE:BOOL=ON \
        -DSG_MODULE_GENERATE:BOOL=ON \
        -DSG_MODULE_DYNAMICS:BOOL=ON \
        -DSG_MODULE_VISUALIZE:BOOL=OFF \
        -DSG_MODULE_VISUALIZE_WITH_QT:BOOL=OFF \
        # TODO: Switch these two ON when CMake is at least 3.15 and remove Boost_ROOT
        # -DCMAKE_FIND_PACKAGE_PREFER_CONFIG:BOOL=ON \
        # -DBoost_DIR:STRING=${BOOST_CMAKE_CONFIG_FOLDER} \
        -DBOOST_ROOT=${BOOST_BUILD_DIR} \
        -DITK_DIR:STRING=${ITK_BUILD_DIR} \
        -DDGtal_DIR:STRING=${DGtal_BUILD_DIR} \
        ${SGEXT_SRC_DIR} && \
    ninja && \
    find . -name "*.o" -delete && \
    find ../SGEXT* -depth -name .git -exec rm -rf '{}' \;
ENV PATH="${SGEXT_BUILD_DIR}/cpp-scripts:${PATH}"

# Build-time metadata as defined at http://label-schema.org
ARG BUILD_DATE
ARG IMAGE=sgext-linux
ARG VERSION=latest
ARG VCS_REF
ARG VCS_URL
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name=$IMAGE \
      org.label-schema.version=$VERSION \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.schema-version="1.0" \
      build_command="docker build -f ./deploy/docker/Dockerfile-dockcross-manylinux2014 . -t phcerdan/sgext-linux"
